"""
signals.py — the three detection signals for Provenance Guard.

Each signal answers the same question from a different angle:
"how likely is it that this text was generated by AI?"
and returns a float in [0, 1] where 0 = clearly human and 1 = clearly AI.

Signal 1  (llm)        -> semantic / holistic judgement (Groq llama-3.3-70b)
Signal 2  (stylometry) -> structural statistics of the prose (pure Python)
Signal 3  (lexical)    -> AI-favoured vocabulary and transition phrases (pure Python)

The signals are deliberately independent: one looks at *meaning*, one at the
*shape* of the writing, one at *word choice*. Where they agree we can be more
confident; where they disagree the ensemble lands near 0.5 (genuinely unsure),
which is exactly what we want a transparency system to admit.
"""

import os
import re
import json
import math

# --------------------------------------------------------------------------- #
#  Shared text helpers
# --------------------------------------------------------------------------- #

_SENTENCE_SPLIT = re.compile(r"[.!?]+(?:\s+|$)")
_WORD = re.compile(r"[A-Za-z']+")


def _sentences(text):
    parts = [s.strip() for s in _SENTENCE_SPLIT.split(text) if s.strip()]
    return parts or [text.strip()]


def _words(text):
    return _WORD.findall(text.lower())


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# --------------------------------------------------------------------------- #
#  Signal 1 — LLM semantic judgement (Groq)
# --------------------------------------------------------------------------- #

_LLM_SYSTEM = (
    "You are a forensic text analyst. You judge whether a passage was most "
    "likely written by a human or generated by an AI language model. You weigh "
    "semantic coherence, idea development, voice, and the presence of lived, "
    "specific detail vs. generic, evenly-hedged prose. You are calibrated and "
    "humble: when a passage is genuinely ambiguous you say so rather than "
    "guessing. Respond ONLY with minified JSON."
)

_LLM_USER_TEMPLATE = (
    "Assess the following passage. Return JSON with exactly these keys:\n"
    '  "ai_likelihood": a float from 0.0 (certainly a human wrote this) to '
    "1.0 (certainly AI-generated),\n"
    '  "reasoning": one short sentence.\n\n'
    "Passage:\n\"\"\"\n{text}\n\"\"\""
)


def signal_llm(text):
    """
    Returns: {"available": bool, "score": float|None, "reasoning": str}

    Tries a real Groq call. If the network/key is unavailable it returns
    available=False so the ensemble can re-weight around it. Setting the
    environment variable MOCK_LLM=1 returns a deterministic offline stub
    (used for testing without burning API calls or network access).
    """
    if os.environ.get("MOCK_LLM") == "1":
        # Offline test stub: approximate a semantic judgement from the two
        # structural signals so the full ensemble can be exercised without a
        # live model. This is for testing only and is clearly labelled as such.
        stylo = signal_stylometry(text)["score"]
        lex = signal_lexical(text)["score"]
        score = _clamp(0.6 * stylo + 0.4 * lex)
        return {"available": True, "score": round(score, 3),
                "reasoning": "MOCK_LLM stub (offline test mode)."}

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {"available": False, "score": None,
                "reasoning": "GROQ_API_KEY not set."}

    try:
        from groq import Groq
        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": _LLM_SYSTEM},
                {"role": "user", "content": _LLM_USER_TEMPLATE.format(text=text)},
            ],
            temperature=0.0,
            max_tokens=120,
            response_format={"type": "json_object"},
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        score = _clamp(float(data.get("ai_likelihood")))
        return {"available": True, "score": round(score, 3),
                "reasoning": str(data.get("reasoning", ""))[:200]}
    except Exception as exc:  # network down, bad key, malformed JSON, etc.
        return {"available": False, "score": None,
                "reasoning": f"LLM unavailable: {type(exc).__name__}"}


# --------------------------------------------------------------------------- #
#  Signal 2 — Stylometric heuristics (structural)
# --------------------------------------------------------------------------- #

def signal_stylometry(text):
    """
    Measures how *uniform* the prose is. AI text tends to be smooth and even;
    human writing is burstier and more irregular. Three sub-metrics:

      burstiness   - coefficient of variation of sentence length.
                     Low variation  -> more AI-like.
      ttr          - type-token ratio (vocabulary diversity), length-corrected.
      punct_var    - variety of punctuation marks used.
                     Humans reach for dashes, ellipses, parentheses; AI prose
                     leans on plain commas and full stops.

    Returns: {"score": float, "metrics": {...}}
    """
    sents = _sentences(text)
    words = _words(text)
    n_words = max(len(words), 1)

    # --- burstiness: coefficient of variation of sentence word-counts -------
    lengths = [len(_words(s)) for s in sents]
    if len(lengths) >= 2 and sum(lengths) > 0:
        mean = sum(lengths) / len(lengths)
        var = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        cv = (math.sqrt(var) / mean) if mean else 0.0
    else:
        cv = 0.0  # single sentence -> no information about variation
    # cv ~0.0 (very uniform) -> AI-like(1.0); cv >=0.6 (varied) -> human(0.0)
    burst_ai = _clamp(1.0 - (cv / 0.6))

    # --- type-token ratio ---------------------------------------------------
    ttr = len(set(words)) / n_words
    # very low diversity (lots of repetition) OR a suspiciously "textbook"
    # mid-high uniform diversity both read slightly AI; extreme casual variety
    # reads human. We map a moderate, tidy TTR (~0.55-0.75) toward AI and a
    # very high or very low TTR toward human/uncertain. Kept gentle on purpose.
    ttr_ai = _clamp(1.0 - abs(ttr - 0.62) / 0.38)
    # short texts make TTR unreliable -> damp its influence
    if n_words < 40:
        ttr_ai *= 0.5

    # --- punctuation variety ------------------------------------------------
    distinct_punct = len(set(ch for ch in text if ch in ",;:—–-()\"'…!?"))
    # 0-1 distinct kinds -> plain -> AI-ish; 4+ kinds -> human-ish
    punct_ai = _clamp(1.0 - (distinct_punct / 4.0))

    # Combine the three sub-metrics. Burstiness is the most reliable single
    # structural tell, so it carries the most weight.
    score = _clamp(0.55 * burst_ai + 0.20 * ttr_ai + 0.25 * punct_ai)

    return {
        "score": round(score, 3),
        "metrics": {
            "sentence_count": len(sents),
            "word_count": len(words),
            "length_cv": round(cv, 3),
            "type_token_ratio": round(ttr, 3),
            "distinct_punctuation": distinct_punct,
            "burstiness_ai": round(burst_ai, 3),
            "ttr_ai": round(ttr_ai, 3),
            "punct_ai": round(punct_ai, 3),
        },
    }


# --------------------------------------------------------------------------- #
#  Signal 3 — Lexical AI-marker density (word choice)
# --------------------------------------------------------------------------- #

# Phrases and words disproportionately common in LLM output. Not proof on their
# own — a human can write "furthermore" — but density is informative.
_AI_PHRASES = [
    "it is important to note", "it is worth noting", "it's worth noting",
    "in today's world", "in conclusion", "in summary", "that being said",
    "plays a crucial role", "plays a vital role", "plays a significant role",
    "when it comes to", "navigating the", "a testament to", "the realm of",
    "in the realm of", "it is essential to", "it is crucial to",
    "on the other hand", "as a result", "in order to",
]
_AI_WORDS = [
    "furthermore", "moreover", "additionally", "consequently", "therefore",
    "delve", "tapestry", "underscore", "underscores", "paradigm", "leverage",
    "robust", "seamless", "seamlessly", "holistic", "multifaceted",
    "nuanced", "intricate", "pivotal", "comprehensive", "transformative",
    "myriad", "realm", "foster", "fostering", "endeavor", "utilize",
]


def signal_lexical(text):
    """
    Counts AI-favoured transition phrases and vocabulary, then scales by length
    so a long human essay isn't punished for using one "however".

    Returns: {"score": float, "markers": [...], "marker_count": int}
    """
    low = text.lower()
    words = _words(text)
    n_words = max(len(words), 1)

    found = []
    for ph in _AI_PHRASES:
        c = low.count(ph)
        if c:
            found.append((ph, c))
    word_set = {}
    for w in words:
        if w in _AI_WORDS:
            word_set[w] = word_set.get(w, 0) + 1
    found.extend(sorted(word_set.items()))

    total_hits = sum(c for _, c in found)
    # markers per 100 words; ~2+ per 100 words is a strong lexical signal
    density = total_hits / n_words * 100.0
    score = _clamp(density / 2.5)
    # short texts: a single marker shouldn't max the signal
    if n_words < 30:
        score *= 0.6

    return {
        "score": round(score, 3),
        "markers": [m for m, _ in found],
        "marker_count": total_hits,
        "markers_per_100w": round(density, 2),
    }


# --------------------------------------------------------------------------- #
#  Ensemble — combine the three signals into one calibrated confidence
# --------------------------------------------------------------------------- #

# Base weights (when the LLM signal is available). The LLM carries the most
# weight because semantic judgement is the strongest single signal; the two
# structural signals act as an independent cross-check that can pull a confident
# LLM verdict back toward "uncertain" when the writing itself looks human.
_WEIGHTS = {"llm": 0.50, "stylometry": 0.30, "lexical": 0.20}


def run_ensemble(text):
    """
    Runs all three signals and combines them into a single confidence in [0,1]
    representing the system's estimated probability the text is AI-generated.

    Returns a dict with the combined confidence, each signal's score, the
    weighting actually used, and a simple majority "vote" for transparency.
    """
    llm = signal_llm(text)
    stylo = signal_stylometry(text)
    lex = signal_lexical(text)

    scores = {"stylometry": stylo["score"], "lexical": lex["score"]}
    if llm["available"]:
        scores["llm"] = llm["score"]
        weights = dict(_WEIGHTS)
    else:
        # Re-normalise the two offline signals to sum to 1 so a missing LLM
        # never silently drags the confidence toward zero.
        s, l = _WEIGHTS["stylometry"], _WEIGHTS["lexical"]
        tot = s + l
        weights = {"stylometry": s / tot, "lexical": l / tot}

    confidence = sum(scores[k] * weights[k] for k in weights)
    confidence = round(_clamp(confidence), 3)

    # Transparency-only majority vote: how many signals individually call it AI?
    votes = sum(1 for v in scores.values() if v >= 0.5)
    vote_str = f"{votes}/{len(scores)} signals lean AI"

    return {
        "confidence": confidence,
        "signals": {
            "llm": llm,
            "stylometry": stylo,
            "lexical": lex,
        },
        "weights_used": {k: round(v, 3) for k, v in weights.items()},
        "vote": vote_str,
    }
